# Varnish Configuration Variables
upstream: <REPLACE_ME> #choose cvmfs or frontier
varnish_site: <REPLACE_ME>
varnish_instance: <REPLACE_ME> 
varnish_transient_mem: 500M #Change to Match System
varnish_mem: 8G #Change to Match System
varnish_port: 6081

