---
# install_certificates.yaml

- name: define certificate variables
  set_fact:
    htcondor_cert: "/etc/letsencrypt/live/{{ ansible_fqdn }}/cert.pem"
    htcondor_key: "/etc/letsencrypt/live/{{ ansible_fqdn }}/privkey.pem"

- name: create grid-security directory
  file:
    path: /etc/grid-security
    state: directory
    mode: '0755'

- name: create mysql globus directory
  file:
    path: /var/lib/mysql/.globus
    state: directory
    owner: mysql
    group: mysql
    mode: '0700'
  ignore_errors: yes 

- name: install x509 certificates 
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
    remote_src: yes 
  with_items:
    - {src: "{{ htcondor_cert }}", dest: "/var/lib/mysql/.globus/usercert.pem", owner: "mysql", group: "mysql", mode: "0400"}
    - {src: "{{ htcondor_cert }}", dest: "/etc/grid-security/hostcert.pem", owner: "root", group: "root", mode: "0644"}
  when:
    - htcondor_cert is defined
    - htcondor_key is defined

- name: install x509 keys 
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
    remote_src: yes 
  with_items:
    - {src: "{{ htcondor_key }}", dest: "/var/lib/mysql/.globus/userkey.pem", owner: "mysql", group: "mysql", mode: "0400"}
    - {src: "{{ htcondor_key }}", dest: "/etc/grid-security/hostkey.pem", owner: "root", group: "root", mode: "0600"}
  when:
    - htcondor_cert is defined
    - htcondor_key is defined

- name: install influxdb certificates
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: "0644"
    remote_src: yes
  with_items:
    - {src: "{{ htcondor_cert }}", dest: "/etc/ssl/hostcert.pem"}
    - {src: "{{ htcondor_key }}", dest: "/etc/ssl/hostkey.pem"}
